name: build-firmware
on:
  push:
    paths:
      - firmware/**
      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
    # branches:
    #   - 'main'
jobs:
  autotag:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        uses: paulhatch/semantic-version@v5.0.2
        id: semver
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"
          change_path: "firmware"
      -
        name: Tag and push current repo code
        run: |
          git tag ${{ steps.semver.outputs.version_tag }}
          git push origin ${{ steps.semver.outputs.version_tag }}
  buildx:
    needs: autotag
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=sha
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ["linux/amd64", "linux/arm64"]
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./firmware
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cherry-firmware:latest
          cache-to: type=inline
